name: Run Selenium Pytest
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest


    steps:
      # Get code form repo
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
      
      # Install Google Chrome
      - name: Install Google Chrome
        run: |
          sudo apt-get update -y
          sudo apt-get install -y google-chrome-stable


      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      # Run tests with pytest
      - name: Run smoke tests
        run: |
          pytest -m smoke --maxfail=1 --disable-warnings -q